# Generated by Django 4.1 on 2025-03-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='example_image.png', max_length=200)),
                ('filetype', models.CharField(default='image/png', max_length=30)),
                ('path', models.ImageField(upload_to='.')),
                ('width', models.IntegerField(default=320)),
                ('height', models.IntegerField(default=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modality', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('pixel_spacing', models.CharField(blank=True, max_length=50, null=True)),
                ('protocol_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mri_type', models.CharField(blank=True, max_length=20, null=True)),
                ('orientation', models.CharField(blank=True, max_length=20, null=True)),
                ('repetition_time', models.CharField(blank=True, max_length=20, null=True)),
                ('echo_time', models.CharField(blank=True, max_length=20, null=True)),
                ('inversion_time', models.CharField(blank=True, max_length=20, null=True)),
                ('flip_angle', models.CharField(blank=True, max_length=20, null=True)),
                ('magnetic_field_strength', models.CharField(blank=True, max_length=20, null=True)),
                ('acquisition_matrix', models.CharField(blank=True, max_length=50, null=True)),
                ('pixel_bandwidth', models.CharField(blank=True, max_length=20, null=True)),
                ('fov', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_module', models.CharField(blank=True, default='segmentation', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_inst', models.CharField(blank=True, default='1', max_length=300)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportName', models.CharField(default='', max_length=200)),
                ('reprotID', models.CharField(default='1', max_length=100)),
                ('reportContent', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UNetMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_img_filename', models.CharField(default='example_mask.png', max_length=200)),
                ('mask_img_path', models.ImageField(default='image/mask', upload_to='.')),
                ('mask_npy_filename', models.CharField(default='example_mask.npy', max_length=200)),
                ('mask_npy_path', models.CharField(default='media/example_mask.npy', max_length=200)),
                ('width', models.IntegerField(default=320)),
                ('height', models.IntegerField(default=320)),
                ('mask_version', models.CharField(default='original', max_length=20)),
                ('edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UNetMaskStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(default='', max_length=50)),
                ('filename', models.CharField(default='', max_length=200)),
                ('path', models.ImageField(default='image/mask', upload_to='.')),
                ('width', models.IntegerField(default=320)),
                ('height', models.IntegerField(default=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unet_mask', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='AutoRad.unetmask')),
            ],
        ),
    ]
