# Generated by Django 4.2.11 on 2024-09-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.CharField(default='000000000000', max_length=100)),
                ('patientName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='imgclass',
            name='docID',
        ),
        migrations.RemoveField(
            model_name='maskclass',
            name='imageID',
        ),
        migrations.RemoveField(
            model_name='maskclass',
            name='maskProperty',
        ),
        migrations.RemoveField(
            model_name='reprotclass',
            name='imgId',
        ),
        migrations.AddField(
            model_name='imgclass',
            name='format',
            field=models.CharField(default='jpg', max_length=10),
        ),
        migrations.AddField(
            model_name='imgclass',
            name='height',
            field=models.IntegerField(default=320, help_text='height in px'),
        ),
        migrations.AddField(
            model_name='imgclass',
            name='imgKey',
            field=models.CharField(default='000000000000', help_text='The public ID of the upoloaded file.', max_length=100),
        ),
        migrations.AddField(
            model_name='imgclass',
            name='patientID',
            field=models.CharField(default='0000000000', max_length=100),
        ),
        migrations.AddField(
            model_name='imgclass',
            name='width',
            field=models.IntegerField(default=320, help_text='Width in px'),
        ),
        migrations.AddField(
            model_name='maskclass',
            name='maskAngle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maskclass',
            name='maskCornerColor',
            field=models.CharField(default='#0000ff', help_text='The color code for corner', max_length=7),
        ),
        migrations.AddField(
            model_name='maskclass',
            name='maskKey',
            field=models.CharField(default='000000000000', help_text='The internal ID of the mask.', max_length=100),
        ),
        migrations.AddField(
            model_name='maskclass',
            name='maskLeft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maskclass',
            name='maskOpacity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='maskclass',
            name='maskPts',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.AddField(
            model_name='maskclass',
            name='maskScale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='maskclass',
            name='maskStrokeColor',
            field=models.CharField(default='#ff0000', help_text='The color code for line', max_length=7),
        ),
        migrations.AddField(
            model_name='maskclass',
            name='maskTop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reprotclass',
            name='reprotID',
            field=models.CharField(default='000000000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='imgclass',
            name='imgName',
            field=models.CharField(help_text='The name of the uploaded image.', max_length=100),
        ),
        migrations.AlterField(
            model_name='imgclass',
            name='reportID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maskclass',
            name='maskName',
            field=models.CharField(help_text='The name of the mask', max_length=200),
        ),
        migrations.AlterField(
            model_name='maskclass',
            name='maskType',
            field=models.CharField(help_text='The type of the mask, ', max_length=200),
        ),
    ]
