# Generated by Django 4.1 on 2025-03-25 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AutoRad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unetmaskstructure',
            name='user',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unetmask',
            name='MRI',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to='AutoRad.mri'),
        ),
        migrations.AddField(
            model_name='unetmask',
            name='edited_by',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mri',
            name='Patient',
            field=models.ForeignKey(blank=True, default='-1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='AutoRad.patient'),
        ),
        migrations.AddField(
            model_name='mri',
            name='user',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
