# Generated by Django 4.1 on 2025-03-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='from_module',
            field=models.CharField(blank=True, default='segmentation', max_length=50, null=True),
        ),
    ]
