# Generated by Django 4.1 on 2025-03-26 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AutoRad', '0003_patient_from_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mri',
            name='uploaded_module',
        ),
        migrations.RemoveField(
            model_name='unetmaskstructure',
            name='user',
        ),
        migrations.AddField(
            model_name='mri',
            name='annotator_inst',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mri',
            name='module',
            field=models.CharField(blank=True, choices=[('Segmentation', 'Segmentation'), ('Assessment/Reporting', 'Assessment/Reporting')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='from_module',
            field=models.CharField(blank=True, choices=[('Segmentation', 'Segmentation'), ('Assessment/Reporting', 'Assessment/Reporting')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unetmask',
            name='edited_by',
            field=models.ForeignKey(blank=True, default='-1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
