# Generated by Django 4.2.11 on 2024-09-10 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AutoRad', '0003_reportclass_delete_reprotclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maskclass',
            name='maskFile',
        ),
        migrations.AlterField(
            model_name='imgclass',
            name='imgName',
            field=models.CharField(default='', help_text='The name of the uploaded image.', max_length=100),
        ),
        migrations.AlterField(
            model_name='imgclass',
            name='reportID',
            field=models.ForeignKey(default='000000000000', on_delete=django.db.models.deletion.CASCADE, to='AutoRad.reportclass'),
        ),
        migrations.AlterField(
            model_name='maskclass',
            name='imgID',
            field=models.ForeignKey(default='000000000000', on_delete=django.db.models.deletion.CASCADE, to='AutoRad.imgclass'),
        ),
        migrations.AlterField(
            model_name='maskclass',
            name='maskName',
            field=models.CharField(default='', help_text='The name of the mask', max_length=200),
        ),
        migrations.AlterField(
            model_name='maskclass',
            name='maskType',
            field=models.CharField(default='', help_text='The type of the mask, ', max_length=200),
        ),
        migrations.AlterField(
            model_name='patientclass',
            name='patientName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientclass',
            name='userID',
            field=models.OneToOneField(default='000000000000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportclass',
            name='patientID',
            field=models.ForeignKey(default='000000000000', on_delete=django.db.models.deletion.CASCADE, to='AutoRad.patientclass'),
        ),
        migrations.AlterField(
            model_name='reportclass',
            name='reportContent',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reportclass',
            name='reportName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
