# Generated by Django 4.2.11 on 2024-09-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0004_remove_maskclass_maskfile_alter_imgclass_imgname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgclass',
            name='imgFile',
            field=models.ImageField(upload_to='media'),
        ),
    ]
