# Generated by Django 4.2.20 on 2025-05-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0004_remove_mri_uploaded_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='annotator_inst',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
