# Generated by Django 4.2.11 on 2024-09-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0005_alter_imgclass_imgfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgclass',
            name='reportID',
        ),
        migrations.AlterField(
            model_name='imgclass',
            name='format',
            field=models.CharField(default='image/png', max_length=10),
        ),
        migrations.AlterField(
            model_name='imgclass',
            name='imgFile',
            field=models.ImageField(upload_to='.'),
        ),
        migrations.AlterField(
            model_name='imgclass',
            name='url',
            field=models.CharField(default='./media', max_length=100),
        ),
    ]
