# Generated by Django 4.2.20 on 2025-05-29 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AutoRad', '0005_patient_annotator_inst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('x', models.FloatField(help_text='Left coordinate, normalized [0–1]')),
                ('y', models.FloatField(help_text='Top coordinate, normalized [0–1]')),
                ('width', models.FloatField(help_text='Width, normalized [0–1]')),
                ('height', models.FloatField(help_text='Height, normalized [0–1]')),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='mri',
            name='lumbar_level',
            field=models.CharField(blank=True, choices=[('L1-L2', 'L1-L2'), ('L2-L3', 'L2-L3'), ('L3-L4', 'L3-L4'), ('L4-L5', 'L4-L5'), ('L5-S1', 'L5-S1')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessment_comments',
            name='MRI',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to='AutoRad.mri'),
        ),
        migrations.AddField(
            model_name='assessment_comments',
            name='Patient',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to='AutoRad.patient'),
        ),
        migrations.AddField(
            model_name='assessment_comments',
            name='user',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
