# Generated by Django 4.2.11 on 2024-09-26 08:44

import AutoRad.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0007_remove_imgclass_created_at_remove_imgclass_imgkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imgclass',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imgclass',
            name='patientID',
            field=models.ForeignKey(default='000000000000', on_delete=django.db.models.deletion.CASCADE, to='AutoRad.patientclass'),
        ),
        migrations.AddField(
            model_name='imgclass',
            name='reportID',
            field=models.ForeignKey(default='000000000000', on_delete=django.db.models.deletion.CASCADE, to='AutoRad.reportclass'),
        ),
        migrations.AddField(
            model_name='maskclass',
            name='maskFile',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='imgclass',
            name='imgFile',
            field=models.ImageField(upload_to=AutoRad.models.userFolder),
        ),
    ]
