# Generated by Django 4.2.11 on 2024-09-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0009_alter_imgclass_imgfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgclass',
            name='patientID',
        ),
        migrations.RemoveField(
            model_name='imgclass',
            name='reportID',
        ),
    ]
