# Generated by Django 4.2.11 on 2024-09-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0014_alter_imgclass_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgclass',
            old_name='userID',
            new_name='user',
        ),
    ]
