# Generated by Django 4.2.11 on 2024-09-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0015_rename_userid_imgclass_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgclass',
            name='user',
        ),
    ]
