# Generated by Django 4.2.11 on 2024-09-26 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AutoRad', '0019_remove_imgclass_user_alter_imgclass_imgfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgclass',
            name='user',
            field=models.ForeignKey(default='000000000000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
