# Generated by Django 4.2.11 on 2024-09-26 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0022_alter_imgclass_imgfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgclass',
            old_name='user',
            new_name='userAcc',
        ),
    ]
