# Generated by Django 4.2.11 on 2024-09-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0024_remove_reportclass_patientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgclass',
            name='userAcc',
        ),
    ]
