# Generated by Django 4.2.11 on 2024-09-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0025_remove_imgclass_useracc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgclass',
            name='format',
        ),
        migrations.RemoveField(
            model_name='imgclass',
            name='height',
        ),
        migrations.RemoveField(
            model_name='imgclass',
            name='width',
        ),
    ]
