# Generated by Django 4.2.11 on 2024-09-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0026_remove_imgclass_format_remove_imgclass_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgclass',
            name='height',
            field=models.IntegerField(default=320, help_text='height in px'),
        ),
        migrations.AddField(
            model_name='imgclass',
            name='type',
            field=models.CharField(default='image/*', max_length=10),
        ),
        migrations.AddField(
            model_name='imgclass',
            name='width',
            field=models.IntegerField(default=320, help_text='Width in px'),
        ),
    ]
