# Generated by Django 4.2.11 on 2024-09-30 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0027_imgclass_height_imgclass_type_imgclass_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='testClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(default='John', max_length=10)),
                ('ln', models.CharField(default='Doe', max_length=10)),
                ('userID', models.ForeignKey(default='0000000', on_delete=django.db.models.deletion.CASCADE, to='AutoRad.imgclass')),
            ],
        ),
    ]
