# Generated by Django 4.2.11 on 2024-09-30 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AutoRad', '0028_testclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgclass',
            name='userAcc',
            field=models.ForeignKey(default='000000000000', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testclass',
            name='userID',
            field=models.ForeignKey(default='000000000000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
