# Generated by Django 4.2.11 on 2024-09-30 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AutoRad', '0029_imgclass_useracc_alter_testclass_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgclass',
            name='userAcc',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maskclass',
            name='imgID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='AutoRad.imgclass'),
        ),
        migrations.AlterField(
            model_name='maskclass',
            name='maskKey',
            field=models.CharField(default='1', help_text='The internal ID of the mask.', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientclass',
            name='patientID',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='reportclass',
            name='reprotID',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='testclass',
            name='userID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
