# Generated by Django 4.2.11 on 2025-01-09 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0031_remove_maskclass_maskkey_alter_imgclass_imgname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='patternClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patternName', models.CharField(default='example_mask.png', help_text='The name of the pattern', max_length=200)),
                ('patternType', models.CharField(default='Default', help_text='The type of the pattern, ', max_length=200)),
                ('patternPts', models.CharField(default='[]', max_length=1000)),
                ('patternTop', models.IntegerField(default=0)),
                ('patternLeft', models.IntegerField(default=0)),
                ('patternAngle', models.FloatField(default=0.0)),
                ('patternScale', models.FloatField(default=1.0)),
                ('patternOpacity', models.FloatField(default=0.5)),
                ('patternCornerColor', models.CharField(default='#0000ff', help_text='The color code for corner', max_length=7)),
                ('patternStrokeColor', models.CharField(default='#ff0000', help_text='The color code for line', max_length=7)),
                ('maskID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='AutoRad.imgclass')),
            ],
        ),
        migrations.AlterField(
            model_name='maskclass',
            name='imgID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='AutoRad.imgclass'),
        ),
        migrations.AlterField(
            model_name='maskclass',
            name='maskOpacity',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='maskclass',
            name='maskType',
            field=models.CharField(default='Default', help_text='The type of the mask, ', max_length=200),
        ),
        migrations.DeleteModel(
            name='testClass',
        ),
    ]
