# Generated by Django 5.0.1 on 2025-01-15 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0031_remove_maskclass_maskkey_alter_imgclass_imgname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maskclass',
            name='imgID',
        ),
        migrations.CreateModel(
            name='MRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='example_image.png', max_length=200)),
                ('filetype', models.CharField(default='image/png', max_length=30)),
                ('path', models.ImageField(upload_to='.')),
                ('width', models.IntegerField(default=320)),
                ('height', models.IntegerField(default=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UNetMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='example_mask.png', max_length=200)),
                ('path', models.CharField(help_text='Path to the file', max_length=200)),
                ('width', models.IntegerField(default=320)),
                ('height', models.IntegerField(default=320)),
                ('mask_version', models.CharField(default='original', max_length=20)),
                ('edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('MRI', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='AutoRad.mri')),
            ],
        ),
        migrations.CreateModel(
            name='UNetMaskStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(default='', max_length=50)),
                ('filename', models.CharField(default='', max_length=200)),
                ('width', models.IntegerField(default=320)),
                ('height', models.IntegerField(default=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unet_mask', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='AutoRad.unetmask')),
            ],
        ),
        migrations.DeleteModel(
            name='imgClass',
        ),
        migrations.DeleteModel(
            name='maskClass',
        ),
    ]
