# Generated by Django 5.0.1 on 2025-01-17 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0032_remove_maskclass_imgid_mri_unetmask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='unetmask',
            old_name='filename',
            new_name='mask_img_filename',
        ),
        migrations.RemoveField(
            model_name='unetmask',
            name='path',
        ),
        migrations.AddField(
            model_name='unetmask',
            name='mask_img_path',
            field=models.ImageField(default='image/mask', upload_to='.'),
        ),
        migrations.AddField(
            model_name='unetmask',
            name='mask_npy_filename',
            field=models.CharField(default='example_mask.npy', max_length=200),
        ),
        migrations.AddField(
            model_name='unetmask',
            name='mask_npy_path',
            field=models.CharField(default='media/example_mask.npy', max_length=200),
        ),
        migrations.AlterField(
            model_name='mri',
            name='user',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unetmask',
            name='MRI',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to='AutoRad.mri'),
        ),
    ]
