# Generated by Django 4.2.11 on 2025-01-10 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0032_patternclass_alter_maskclass_imgid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patternclass',
            name='maskID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='AutoRad.maskclass'),
        ),
    ]
