# Generated by Django 5.0.1 on 2025-01-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoRad', '0033_rename_filename_unetmask_mask_img_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unetmaskstructure',
            name='path',
            field=models.ImageField(default='image/mask', upload_to='.'),
        ),
    ]
